### ISSUE TITLE
Change output directory of exports

### ISSUE THREAD

**Issue by bravokiloecho** [raphaelameaume/fragment#22]
Is it possible to change the directory where the exports (images, videos, builds) are created?

**Comment by raphaelameaume** [comment]
This is not currently possible but it's been on the roadmap for a while!
I'm curious what you'd like to be possible? Per sketch configuration ? Global configuration ?

**Comment by bravokiloecho** [comment]
Oh nice!

What I imagine would be nice, is a global config that could be defined in the root of the fragment directory. And then have the option to override this setting on a sketch-by-sketch basis by exporting a config from each sketch's JS file (similar to how you can currently define the filename structure).

Does that make sense / sound reasonable?

**Comment by bravokiloecho** [comment]
In case anyone was having the same issue as me, I came up with a pretty simple solution to solve my original problem of wanting to git ignore rendered images and videos.

Adding these lines to the `.gitgnore` file allows you to commit any `.png` or `.mp4` file as long as they are in the `gfx/` directory (name this what you want) but ignores any of these types of files elsewhere (ie, the rendered ones):

```
*.png
*.mp4
!/gfx/*.png
!/gfx/*.mp4
```

**Comment by raphaelameaume** [comment]
Hello @bravokiloecho. Apologies for the delay to bring this feature made months ago in a new proper release. You can now use a flag `exportDir` as described in #37.

Cheers!

**Comment by bravokiloecho** [comment]
Amazing! Thank you so much, and I really appreciate you letting me know here.

The feature looks great and definitely resolves the issue I had.

Is the architecture of this solution different to what would be needed if we wanted to define the output directory as an export in the sketch file. For example, adding something like:

```
export const exportDir = '../exports/'
```

**Comment by raphaelameaume** [comment]
That's a good idea to allow configuration of this on the sketch file as well. I'll have a look into that.

**Comment by raphaelameaume** [comment]
Hello @bravokiloecho! Maybe merged too quickly but I've added an `exportDir` exports from the sketch file as a possible way to change the exports directory. Can you have a [look at it](https://github.com/raphaelameaume/fragment/pull/49 ) even if it's merged in dev already? 
Let me know what you think!

**Comment by bravokiloecho** [comment]
Amazing! I tried pulling the fragment repo and running on my machine with this command:

```
node /Users/ben/Documents/personal-repos/fragment/bin/index.js audio-responsive-2/index.js
```

and adding this to the sketch file (I also tried an absolute path):

```
export let exportDir = `../exports/`
```

but the export was saved in the Downloads directory.

Not sure if I did something wrong here....

**Comment by raphaelameaume** [comment]
Which OS are you running? That's weird, I don't see how this could end up in the Downloads directory as there is no fallback to that... 
If you remove `export let exportDir = `../exports/`, where does it save ?

One thing that could be the source of the problem might be not running the command and using the path to the command line instead, I'll have a look

**Comment by bravokiloecho** [comment]
I'm using Mac OS 12.5.1

If I remove the `exportDir` line in the sketch file it saves in the file's directory (as standard)

**Comment by raphaelameaume** [comment]
I tested on an other Mac and I wasn't able to reproduce the error. Would you be able to make a screen recording of the flow where it saves in the Downloads folder?

**Comment by raphaelameaume** [comment]
Any news @bravokiloecho ?

**Comment by raphaelameaume** [comment]
This was fixed in https://github.com/raphaelameaume/fragment/pull/49 and released in https://github.com/raphaelameaume/fragment/releases/tag/v0.1.14
