### ISSUE TITLE
Is it possible to render SVG? 

### ISSUE THREAD

**Issue by zehfernandes** [raphaelameaume/fragment#38]

**Comment by raphaelameaume** [comment]
Not at the moment but it would be nice to have that at some point! The rendering is pretty tied to a canvas at the moment so I'm not sure of how it could works with SVG yet!

Do you have already an idea of what  a sketch file would look like with `rendering="svg"` ?

**Comment by miguelbermudez** [comment]
What about adding a mode that use this: https://github.com/zenozeng/p5.js-svg

**Comment by raphaelameaume** [comment]
I'd rather add some kind of SVG renderer instead of having SVG based sketches tied to a rendering library. Still not sure about the right way to do this though, welcoming suggestions based on the current state of things!

**Comment by klaushubben** [comment]
Could there be a brief "how-to" on adding custom renderers? So things like this don't need to become part of the repo, but up to the user to manage.

**Comment by raphaelameaume** [comment]
Do you mean having the ability to pass along a custom renderer on sketch start or improving docs so it's easier to fork the repo and add a custom renderer in it ?

**Comment by klaushubben** [comment]
they both sound like great options tbh. I'm guessing custom renderers may be more positive for the project moving forward?

**Comment by raphaelameaume** [comment]
Closing this since custom renderers were released in https://github.com/raphaelameaume/fragment/releases/tag/v0.1.14.

The guide also shows how to implement a SVG Renderer as an example. See https://github.com/raphaelameaume/fragment/blob/dev/docs/guide/custom-renderers.md
