### ISSUE TITLE
Bug with threejs dependencies

### ISSUE THREAD

**Issue by Makio64** [raphaelameaume/fragment#39]
Im having issue while trying three template Fragment on windows : 

step 1 : try the command `fragment ./sketch.js --new --template=three/orthographic`
> getting error message ( you should install threejs ) 

step 2 : `npm install three`
> install correctly

step 3 : `fragment ./sketch.js`
> Could not resolve "./E:/github/sketchs/node_modules/three/build/three.module.js"

The error is obviously the ./ at the start of the url.

**Comment by raphaelameaume** [comment]
Closing this as the issue is old and lots have changed since then. Feel free to open a new one if you encounter this type of issue again.
