### ISSUE TITLE
Loading a texture into a fragment shader

### ISSUE THREAD

**Issue by bravokiloecho** [raphaelameaume/fragment#40]
When using the `rendering = "fragment"` option, what's the method for using a texture as a uniform and then rendering it using `texture2D`?

**Comment by raphaelameaume** [comment]
You can import a Texture class like this:

```js
import { Texture } from "fragment/lib/gl";

let uniforms = {
  texture:  { value: null, type: "sampler2d" },
}

export let init = ({ frag }) => {
  let image = new Image();
  let texture = new Texture(frag.gl, { image });
 
  image.onload = () => texture.needsUpdate = true;
  image.src = url;
  
  uniforms.texture.value = texture;
};
```

You can see which parameters you can pass on here: https://github.com/raphaelameaume/fragment/blob/main/src/client/app/lib/gl/Texture.js

**Comment by bravokiloecho** [comment]
Amazing! That's super helpful, thank you 🙏
