### ISSUE TITLE
Change canvas orientation

### ISSUE THREAD

**Issue by afternoon2** [raphaelameaume/fragment#63]
Hey! What a great tool you are making! I wanted to add a PR for supporting landscape/portrait canvas orientation which would be useful for example when exporting a sketch to a SVG, to be then drawn using a pen plotter.

I wonder if it's better to include `Landscape`/`Portrait` suffixes to each paper size entry (which would double the number of presets), or maybe to have additional setting that modifies the placement of canvas width and height values for each preset. Wdyt? 🙂

**Comment by raphaelameaume** [comment]
Hello! Thanks for the kind words! I'm not quite sure to understand what you're describing, can't it be solved by changing width/height of the canvas? Is is just when using paper sizes ? In this case, that could be a toggle/switch when using preset sizes, the list of presets is already quite long and I would like to avoid doubling it by adding landscape/portrait suffixes.

**Comment by afternoon2** [comment]
Yes, it's only a case for paper sizes. And adding a toggle sounds good 👍🏻

**Comment by raphaelameaume** [comment]
I opened a PR https://github.com/raphaelameaume/fragment/pull/65. Would you be able to check it out before it gets merged in dev? Thanks

**Comment by raphaelameaume** [comment]
Fixed in #65 and released in #105
